FROM node:14 AS builder

WORKDIR /usr/src/app

COPY package.json ./

ENV CI=false

RUN npm install

COPY . .

ARG COLDSTACK_S3_ENDPOINT
ARG AUTHNODE_URL
ARG API_URL
ARG DEPOSITING_KEY
ARG WS_API_URL
ARG RPC_API_URL

ENV REACT_APP_COLDSTACK_S3_ENDPOINT=$COLDSTACK_S3_ENDPOINT
ENV REACT_APP_AUTHNODE_URL=$AUTHNODE_URL
ENV REACT_APP_API_URL=$API_URL
ENV REACT_APP_DEPOSITING_KEY=$DEPOSITING_KEY
ENV REACT_APP_WS_API_URL=$WS_API_URL
ENV REACT_APP_RPC_API_URL=$RPC_API_URL
ENV REACT_APP_PORTIS_DAPP_ID=$PORTIS_DAPP_ID

RUN echo REACT_APP_WS_API_URL=$REACT_APP_WS_API_URL
RUN echo REACT_APP_RPC_API_URL=$REACT_APP_RPC_API_URL

RUN npm run build

FROM nginx:1.13.9-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

CMD nginx -g 'daemon off;'
